cask_args appdir: '/Applications'

brew 'curl'
brew 'git'

cask '1password'
cask 'alfred'
cask 'caffeine'
cask 'filezilla'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'java'
cask 'screenhero'
cask 'slack'